language: minimal
if: branch = master

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

script:
  - mkdir -p files-to-gh-pages/stable
  - echo $(pwd)
  - bash ./helm-packages.sh
  - cd files-to-gh-pages/stable
  - helm repo index .
  - ls -ltr

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: files-to-gh-pages/stable
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branche: master
