language: minimal
cache:
  directories:
   - /home/travis/build/albizon/charts/files-to-gh-pages

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

jobs:
  include:
    - stage: build-dev
      if: branch =~ dev-
      script:
        - mkdir -p files-to-gh-pages/stable
        - mkdir -p files-to-gh-pages/dev   
        - cd files-to-gh-pages/stable
        - wget -r https://albizon.github.io/charts/stable
        - cd ../dev 
        - wget -r https://albizon.github.io/charts/dev
        - cd ../..
        - echo $(pwd)
        - bash ./build-dev.sh
        - cd files-to-gh-pages/dev
        - helm repo index .
        - ls -ltr
    - stage: build-stable
      if: branch = master
      script:
        - mkdir -p files-to-gh-pages/stable
        - mkdir -p files-to-gh-pages/dev
        - cd files-to-gh-pages/stable
        - wget -r https://albizon.github.io/charts/stable
        - cd ../dev
        - wget -r https://albizon.github.io/charts/dev
        - cd ../..
        - echo $(pwd)
        - bash ./helm-packages.sh
        - cd files-to-gh-pages/stable
        - helm repo index .
        - ls -ltr
    - stage: deploy-gh-pages
      script: skip
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: files-to-gh-pages
        target_branch: gh-pages
        verbose: true
        skip_cleanup: true
  allow_failures:
    - stage: build-stable
    - stage: build-dev
#deploy:
#  provider: pages
#  github_token: $GITHUB_TOKEN
#  local_dir: files-to-gh-pages
#  target_branch: gh-pages
#  verbose: true
#  skip_cleanup: true
#  keep_history: true
