# Default values for lemonldapNG.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

portail:
  image:
    repository: nginx
    tag: 1.11.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  restartPolicy: Never
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  service:
#    annotations: {}
#    clusterIP: ""
#    externalIPs: []
#    loadBalancerIP: ""
#    loadBalancerSourceRanges: []
    type: ClusterIP
#    nodePort: ""
    
manager:
  image:
    repository: nginx
    tag: 1.11.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  restartPolicy: Never
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  service:
#    annotations: {}
#    clusterIP: ""
#    externalIPs: []
#    loadBalancerIP: ""
#    loadBalancerSourceRanges: []
    type: ClusterIP
#    nodePort: ""
    
db:
  username: "lemonldap"
  password: "lemonldap"
  database: "lemonldap"
  table: "lemonldap-conf"
  host: "lemonldap-postgres"
  port: 5432
    
    
ingress:
  enabled: true
  labels: 
    traffic-type: frontend
  annotations: 
    traefik.ingress.kubernetes.io/preserve-host:  "true" 
  hosts:
  - "sso.example.com"
  tls:
  
  additionalRules: []
  
conf_backend:
  enabled: true
  replication:
    enabled: true
    slaveReplicas: 2
  service:
    port: 5432
    
  
session_backend:
  enabled: true
