{{- $hostname := include "lemonldapNG.conf_backend.hostname" . -}}
{{- $port := include "lemonldapNG.conf_backend.port" . -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "lemonldapNG.fullname" . }}-manager-ini-file
data:

  lemonldap-ng.ini: |
    {{- template "lemonldapNG.ini.global.header" }}
    [configuration]
    type = RDBI
    dbiChain    = DBI:Pg:database={{ .Values.db.database }};host={{ $hostname }};port={{ $port }}"
    dbiUser     = {{ .Values.db.username }}
    dbiPassword = {{ .Values.db.password }}
    dbiTable    = {{ .Values.db.table }}
    {{- template "lemonldapNG.ini.global.localCache" }}
