apiVersion: v1
kind: Service
metadata:
{{- if .Values.portail.service.annotations }}
  annotations:
{{ toYaml .Values.portail.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "lemonldapNG.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "lemonldapNG.portail.fullname" . }}
spec:
# Provides options for the service so chart users have the full choice
  type: "{{ .Values.portail.service.type }}"
  clusterIP: "{{ .Values.portail.service.clusterIP }}"
{{- if .Values.portail.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.portail.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.portail.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.portail.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.portail.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.portail.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      {{- if (and (eq .Values.portail.service.type "NodePort") (not (empty .Values.portail.service.nodePort))) }}
      nodePort: {{ .Values.portail.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "lemonldapNG.portail.name" . }}
release: {{ .Release.Name }}
